spring:
  application:
    name: api-gateway
  profiles:
    active: local

---
spring:

  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: tru
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      discovery:
        locator:
          enabled: true
      routes:
        - id: points
          uri: lb://points
          predicates:
            - Path=/api/v1/points/**
          filters:
            - AuthFilter

        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
  main:
    web-application-type: reactive

  datasource:
    url: jdbc:postgresql://localhost:5432/lab4
    username: awesoma
    password: "1"
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: api-gateway
    instance-id: api-gateway:${random.value}

---
spring:
  config:
    activate:
      on-profile: docker

  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: tru
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      discovery:
        locator:
          enabled: true
      routes:
        - id: points
          uri: lb://points
          predicates:
            - Path=/api/v1/points/**
          filters:
            - AuthFilter

        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
  main:
    web-application-type: reactive

  datasource:
    url: jdbc:postgresql://postgres-db:5432/lab4
    username: awesoma
    password: "1"
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: api-gateway
    instance-id: api-gateway:${random.value}