/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation("commons-cli:commons-cli:1.7.0")
    implementation("io.github.cdimascio:dotenv-java:3.0.0")
}

repositories {
    mavenCentral()
}

description = "common"