package org.awesoma.client.bundles;

import java.util.ListResourceBundle;

public class Language_nl extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"login", "Log ind"},
                {"password", "Adgangskode"},
                {"loginButton", "Log ind"},
                {"cancelButton", "Annuller"},
                {"registerButton", "Registrer"},
                {"language", "Sprog"},
                {"register", "Registrer"},
                {"error", "Fejl"},
                {"info", "Info"},
                {"pleaseEnterLoginAndPassword", "Vul uw login en wachtwoord in:"},
                {"pleaseEnterLogin", "Vul uw login in:"},
                {"pleaseEnterPassword", "Vul uw wachtwoord in:"},
                {"registerSuggestion", "Als u nog geen account hebt, kunt u hier registreren:"},

                {"executeScript", "Script uitvoeren"},
                {"clear", "Wissen"},
                {"help", "Help"},
                {"add", "Toevoegen"},
                {"addIfMax", "Toevoegen (als max)"},
                {"info", "Info"},
                {"removeById", "Verwijderen (op ID)"},
                {"removeAt", "Verwijderen (op positie)"},
                {"update", "Bijwerken"},
                {"logOut", "Uitloggen"},
                {"exit", "Afsluiten"},

                {"id", "ID"},
                {"name", "Naam"},
                {"owner", "Eigenaar"},
                {"creationDate", "Aanmaakdatum"},
                {"operator", "Bestuurder"},
                {"genre", "Genre"},
                {"oscarsCount", "Oscars-aantal"},
                {"totalBoxOffice", "Totale box office"},
                {"language", "Taal"},

                {"opBirthdayLabel", "Geboortedatum van de bestuurder"},
                {"opNameLabel", "Naam van de bestuurder"},
                {"opNameTextField", "Vul uw naam in:"},
                {"opBirthdayTextField", "Vul uw geboortedatum in:"},
                {"ocLabel", "Box office"},
                {"ocTextField", "Vul uw box office in:"},
                {"genreLabel", "Genre"},
                {"genreTextField", "Vul uw genre in:"},
                {"coordinatesLabel", "Koördinaten"},
                {"coordXLabel", "X-koördinaat"},
                {"coordXTextField", "Vul uw X-koördinaat in:"},
                {"coordYLabel", "Y-koördinaat"},
                {"coordYTextField", "Vul uw Y-koördinaat in:"},
                {"operatorLabel", "Bestuurder"},
                {"operatorNameLabel", "Naam van de bestuurder"},
                {"operatorNameTextField", "Vul uw naam in:"},
                {"creationDateLabel", "Aanmaakdatum"},
                {"creationDateTextField", "Vul uw aanmaakdatum in:"},
                {"colorMenuBar", "Kleurmenu"},
                {"redColorMenuItem", "Rood"},
                {"blackColorMenuItem", "Zwart"},
                {"yellowColorMenuItem", "Geel"},
                {"orangeColorMenuItem", "Oranje"},
                {"whiteColorMenuItem", "Wit"},
                {"ukCountryMenuItem", "Verenigd Koninkrijk"},
                {"germanyCountryMenuItem", "Duitsland"},
                {"franceCountryMenuItem", "Frankrijk"},
                {"noneCountryMenuItem1", "Geen"},
                {"cancelButton", "Annuleren"},
                {"okButton", "OK"},
                {"countryMenuBar", "Landsmenu"},
                {"noneCountryMenuItem1", "Geen"},

                {"User:", "Gebruiker:"},
                {"Update", "Bijwerken"},
                {"WrongOwnerException", "Niet de eigenaar van het film"},
                {"NumberFormatException", "Ongeldig nummer"},
                {"NotFoundException", "Film niet gevonden"},
                {"IOException", "Fout bij het lezen van het bestand"},
                {"Can't read file", "Kan het bestand niet lezen"},
                {"ERROR", "FOUT"},
                {"OK", "OK"},
                {"Cancel", "Annuleren"},
                {"Yes", "Ja"},
                {"WARNING", "WAARSCHUWING"},

                {"Movie", "Film"},
                {"Operator", "Bestuurder"},
                {"Genre", "Genre"},
                {"Box office", "Box office"},
                {"Oscars count", "Oscars-aantal"},
                {"Creation date", "Aanmaakdatum"},
                {"Birthday", "Geboortedatum"},
                {"Weight", "Gewicht"},
                {"Eye color", "Augenfarbe"},
                {"Nationality", "Nationaliteit"},

                {"Update", "Bijwerken"},
                {"Remove", "Verwijderen"},
                {"Add", "Toevoegen"},
                {"Add (if max)", "Toevoegen (als max)"},
                {"Update by ID", "Bijwerken op ID"},
                {"Remove by ID", "Verwijderen op ID"},
                {"Remove at", "Verwijderen op positie"},

                {"FileChooserTitle", "Selecteer bestand"},
        };
    }
}
