package org.awesoma.client.bundles;

import java.util.ListResourceBundle;

public class Language_es extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"login", "Iniciar sesión"},
                {"password", "Contraseña"},
                {"loginButton", "Iniciar sesión"},
                {"cancelButton", "Cancelar"},
                {"registerButton", "Registrarse"},
                {"language", "Idioma"},
                {"register", "Registrarse"},
                {"error", "Error"},
                {"info", "Info"},
                {"pleaseEnterLoginAndPassword", "Por favor ingrese su login y contraseña:"},
                {"pleaseEnterLogin", "Por favor ingrese su login:"},
                {"pleaseEnterPassword", "Por favor ingrese su contraseña:"},
                {"registerSuggestion", "Si no tienes cuenta, puedes registrarte aquí:"},

                {"executeScript", "Ejecutar script"},
                {"clear", "Borrar"},
                {"help", "Ayuda"},
                {"add", "Añadir"},
                {"addIfMax", "Añadir (si máximo)"},
                {"info", "Info"},
                {"removeById", "Eliminar (por ID)"},
                {"removeAt", "Eliminar (por posición)"},
                {"update", "Actualizar"},
                {"logOut", "Cerrar sesión"},
                {"exit", "Salir"},

                {"id", "ID"},
                {"name", "Nombre"},
                {"owner", "Propietario"},
                {"creationDate", "Fecha de creación"},
                {"operator", "Operador"},
                {"genre", "Género"},
                {"oscarsCount", "Cantidad de oscar"},
                {"totalBoxOffice", "Total box office"},
                {"language", "Idioma"},

                {"opBirthdayLabel", "Fecha de nacimiento del operador"},
                {"opNameLabel", "Nombre del operador"},
                {"opNameTextField", "Ingrese su nombre:"},
                {"opBirthdayTextField", "Ingrese su fecha de nacimiento:"},
                {"ocLabel", "Box office"},
                {"ocTextField", "Ingrese su box office:"},
                {"genreLabel", "Género"},
                {"genreTextField", "Ingrese su género:"},
                {"coordinatesLabel", "Coordenadas"},
                {"coordXLabel", "X coordenada"},
                {"coordXTextField", "Ingrese su X coordenada:"},
                {"coordYLabel", "Y coordenada"},
                {"coordYTextField", "Ingrese su Y coordenada:"},
                {"operatorLabel", "Operador"},
                {"operatorNameLabel", "Nombre del operador"},
                {"operatorNameTextField", "Ingrese su nombre:"},
                {"creationDateLabel", "Fecha de creación"},
                {"creationDateTextField", "Ingrese su fecha de creación:"},
                {"colorMenuBar", "Menú de color"},
                {"redColorMenuItem", "Rojo"},
                {"blackColorMenuItem", "Negro"},
                {"yellowColorMenuItem", "Amarillo"},
                {"orangeColorMenuItem", "Naranja"},
                {"whiteColorMenuItem", "Blanco"},
                {"ukCountryMenuItem", "Reino Unido"},
                {"germanyCountryMenuItem", "Alemania"},
                {"franceCountryMenuItem", "Francia"},
                {"noneCountryMenuItem1", "Ninguno"},
                {"cancelButton", "Cancelar"},
                {"okButton", "OK"},
                {"countryMenuBar", "Menú de país"},
                {"noneCountryMenuItem1", "Ninguno"},

                {"User:", "Usuario:"},
                {"Update", "Actualizar"},
                {"WrongOwnerException", "No el dueño del filme"},
                {"NumberFormatException", "Número inválido"},
                {"NotFoundException", "Filme no encontrado"},
                {"IOException", "Error leyendo el archivo"},
                {"Can't read file", "No se puede leer el archivo"},
                {"ERROR", "ERROR"},
                {"OK", "OK"},
                {"Cancel", "Cancel"},
                {"WARNING", "WARNING"},

                {"Movie", "Film"},
                {"Operator", "Operador"},
                {"Genre", "Género"},
                {"Box office", "Box office"},
                {"Oscars count", "Cantidad de oscar"},
                {"Creation date", "Fecha de creación"},
                {"Birthday", "Fecha de nacimiento"},
                {"Weight", "Peso"},
                {"Eye color", "Color de la ojo"},
                {"Nationality", "Nacionalidad"},

                {"Update", "Actualizar"},
                {"Remove", "Eliminar"},
                {"Add", "Añadir"},
                {"Add (if max)", "Añadir (si máximo)"},
                {"Update by ID", "Actualizar por ID"},
                {"Remove by ID", "Eliminar por ID"},
                {"Remove at", "Eliminar por posición"},
        };
    }
}
