package org.awesoma.client.bundles;

import org.awesoma.common.commands.AddCommand;
import org.awesoma.common.commands.AddIfMaxCommand;

import java.util.ListResourceBundle;

public class Language_en extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"login", "Login"},
                {"password", "Password"},
                {"loginButton", "Login"},
                {"cancelButton", "Cancel"},
                {"registerButton", "Register"},
                {"language", "Language"},
                {"register", "Register"},
                {"error", "Error"},
                {"info", "Info"},
                {"pleaseEnterLoginAndPassword", "Please enter your login and password:"},
                {"pleaseEnterLogin", "Please enter your login:"},
                {"pleaseEnterPassword", "Please enter your password:"},
                {"registerSuggestion", "If you don't have an account you might want to register here:"},

                {"executeScript", "Execute Script"},
                {"clear", "Clear"},
                {"help", "Help"},
                {"add", "Add"},
                {"addIfMax", "Add (if max)"},
                {"info", "Info"},
                {"removeById", "Remove (by ID)"},
                {"removeAt", "Remove (by position)"},
                {"update", "Update"},
                {"logOut", "Log out"},
                {"exit", "Exit"},

                {"id", "ID"},
                {"name", "Name"},
                {"owner", "Owner"},
                {"creationDate", "Creation date"},
                {"operator", "Operator"},
                {"genre", "Genre"},
                {"oscarsCount", "Oscars count"},
                {"totalBoxOffice", "Total box office"},
                {"language", "Language"},

                {"opBirthdayLabel", "Birthday of the operator"},
                {"opNameLabel", "Name of the operator"},
                {"opNameTextField", "Enter your name:"},
                {"opBirthdayTextField", "Enter your birthday:"},
                {"ocLabel", "Box office"},
                {"ocTextField", "Enter your box office:"},
                {"genreLabel", "Genre"},
                {"genreTextField", "Enter your genre:"},
                {"coordinatesLabel", "Coordinates"},
                {"coordXLabel", "X coordinate"},
                {"coordXTextField", "Enter your X coordinate:"},
                {"coordYLabel", "Y coordinate"},
                {"coordYTextField", "Enter your Y coordinate:"},
                {"operatorLabel", "Operator"},
                {"operatorNameLabel", "Name of the operator"},
                {"operatorNameTextField", "Enter your name:"},
                {"creationDateLabel", "Creation date"},
                {"creationDateTextField", "Enter your creation date:"},
                {"colorMenuBar", "Color menu"},
                {"redColorMenuItem", "Red"},
                {"blackColorMenuItem", "Black"},
                {"yellowColorMenuItem", "Yellow"},
                {"orangeColorMenuItem", "Orange"},
                {"whiteColorMenuItem", "White"},
                {"ukCountryMenuItem", "UK"},
                {"germanyCountryMenuItem", "Germany"},
                {"franceCountryMenuItem", "France"},
                {"noneCountryMenuItem1", "None"},
                {"cancelButton", "Cancel"},
                {"okButton", "OK"},
                {"countryMenuBar", "Country menu"},
                {"noneCountryMenuItem1", "None"},

                {"User:", "User:"},
                {"Update", "Update"},
                {"WrongOwnerException", "Not the owner of the movie"},
                {"NumberFormatException", "Invalid number"},
                {"NotFoundException", "Movie not found"},
                {"IOException", "Error reading file"},
                {"Can't read file", "Can't read file"},
                {"ERROR", "ERROR"},
                {"Error", "Error"},
                {"OK", "OK"},
                {"Cancel", "Cancel"},
                {"WARNING", "WARNING"},
                {"Enter all data", "Enter all data"},

                {"Movie", "Movie"},
                {"Operator", "Operator"},
                {"Genre", "Genre"},
                {"Box office", "Box office"},
                {"Oscars count", "Oscars count"},
                {"Creation date", "Creation date"},
                {"Birthday", "Birthday"},
                {"Weight", "Weight"},
                {"Eye color", "Eye color"},
                {"Nationality", "Nationality"},

                {"Update", "Update"},
                {"Remove", "Remove"},
                {"Add", "Add"},
                {"Add (if max)", "Add (if max)"},
                {"Update by ID", "Update by ID"},
                {"Remove by ID", "Remove by ID"},
                {"Remove at", "Remove at"},

                {"FileChooserTitle", "Select file"},

                {"add", "Add"},
                {"addIfMax", "Add (if max)"},
                {"info", "Info"},
                {"removeById", "Remove (by ID)"},
                {"removeAt", "Remove (by position)"},
                {"update", "Update"},
                {"logOut", "Log out"},
                {"exit", "Exit"},

                {new AddCommand().getName(), "add"},
                {new AddIfMaxCommand().getName(), "addIfMax"},
                {new AddIfMaxCommand().getDescription(), "adds element if it's TBO is max"},

                {"delete", "Delete"},
                {"Movie is not presented", "Movie is not presented"},
                {"Movie", "Movie"},
                {"add", "Add"},
                {"update_id", "Update by ID"},
                {"remove_by_id", "Remove by ID"},
                {"remove_at", "Remove at"},
                {"execute_script", "Execute script"},
                {"clear", "Clear"},
                {"help", "Help"},
                {"add", "Add"},
                {"add_if_max", "Add (if max)"},
                {"info", "Info"},
                {"remove_by_id", "Remove (by ID)"},
                {"remove_at", "Remove (by position)"},
                {"update", "Update"},
                {"log_out", "Log out"},
                {"exit", "Exit"},

                {"Visualization", "Visualization"},
                {"visualization", "Visualization"},

                {"Movie is not presented", "Movie is not presented"},
                {"Movie", "Movie"},
                {"opNameLabel", "Name of the operator"},
                {"opNameTextField", "Enter your name:"},
                {"opBirthdayLabel", "Birthday of the operator"},
                {"opWeightLabel", "Weight"},
                {"ocLabel", "Box office"},
                {"ocTextField", "Enter your box office:"},
                {"genreLabel", "Genre"},
                {"coordinatesLabel", "Coordinates"},
                {"coordXLabel", "X coordinate"},
                {"coordXTextField", "Enter your X coordinate:"},
                {"coordYLabel", "Y coordinate"},
                {"coordYTextField", "Enter your Y coordinate:"},
                {"operatorLabel", "Operator"},
                {"colorMenuBar", "Color menu"},
                {"redColorMenuItem", "Red"},
                {"blackColorMenuItem", "Black"},
                {"yellowColorMenuItem", "Yellow"},
                {"orangeColorMenuItem", "Orange"},
                {"whiteColorMenuItem", "White"},
                {"ukCountryMenuItem", "UK"},
                {"germanyCountryMenuItem", "Germany"},
                {"franceCountryMenuItem", "France"},
                {"noneCountryMenuItem1", "None"},
                {"cancelButton", "Cancel"},
                {"okButton", "OK"},
                {"countryMenuBar", "Country menu"},
                {"noneCountryMenuItem1", "None"},
                {"uboLabel", "Usa Box Office"},
                {"uboTextField", "Enter your box office:"},

                {"weight", "Weight"},
                {"Eye color", "Eye color"},
                {"Nationality", "Nationality"},
                {"movieNameLabel", "Name of the movie"},
                {"movieNameTextField", "Enter your name:"},
                {"movieLabel", "Movie"},

                {"tableTab", "Table"},
                {"visualizationTab", "Visualization"},

                {"lab8", "Lab8"},

        };
    }
}
