package org.awesoma.client.bundles;

import java.util.ListResourceBundle;

public class Language_de extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"login", "Anmelden"},
                {"password", "Passwort"},
                {"loginButton", "Anmelden"},
                {"cancelButton", "Abbrechen"},
                {"registerButton", "Registrieren"},
                {"language", "Sprache"},
                {"register", "Registrieren"},
                {"error", "Fehler"},
                {"info", "Info"},
                {"pleaseEnterLoginAndPassword", "Bitte geben Sie Ihren Login und Ihr Passwort ein:"},
                {"pleaseEnterLogin", "Bitte geben Sie Ihren Login ein:"},
                {"pleaseEnterPassword", "Bitte geben Sie Ihr Passwort ein:"},
                {"registerSuggestion", "Wenn Sie noch keinen Account haben, können Sie sich hier registrieren:"},

                {"executeScript", "Skript ausführen"},
                {"clear", "Löschen"},
                {"help", "Hilfe"},
                {"add", "Hinzufügen"},
                {"addIfMax", "Hinzufügen (wenn maximal)"},
                {"info", "Info"},
                {"removeById", "Entfernen (nach ID)"},
                {"removeAt", "Entfernen (nach Position)"},
                {"update", "Aktualisieren"},
                {"logOut", "Abmelden"},
                {"exit", "Beenden"},

                {"id", "ID"},
                {"name", "Name"},
                {"owner", "Besitzer"},
                {"creationDate", "Erstellungsdatum"},
                {"operator", "Betreiber"},
                {"genre", "Genre"},
                {"oscarsCount", "Oscars-Anzahl"},
                {"totalBoxOffice", "Total Box Office"},
                {"language", "Sprache"},

                {"opBirthdayLabel", "Geburtstag des Betreibers"},
                {"opNameLabel", "Name des Betreibers"},
                {"opNameTextField", "Geben Sie Ihren Namen ein:"},
                {"opBirthdayTextField", "Geben Sie Ihren Geburtstag ein:"},
                {"ocLabel", "Box Office"},
                {"ocTextField", "Geben Sie Ihren Box Office ein:"},
                {"genreLabel", "Genre"},
                {"genreTextField", "Geben Sie Ihren Genre ein:"},
                {"coordinatesLabel", "Koordinaten"},
                {"coordXLabel", "X-Koordinate"},
                {"coordXTextField", "Geben Sie Ihre X-Koordinate ein:"},
                {"coordYLabel", "Y-Koordinate"},
                {"coordYTextField", "Geben Sie Ihre Y-Koordinate ein:"},
                {"operatorLabel", "Betreiber"},
                {"operatorNameLabel", "Name des Betreibers"},
                {"operatorNameTextField", "Geben Sie Ihren Namen ein:"},
                {"creationDateLabel", "Erstellungsdatum"},
                {"creationDateTextField", "Geben Sie Ihren Erstellungsdatum ein:"},
                {"colorMenuBar", "Farbmenü"},
                {"redColorMenuItem", "Rot"},
                {"blackColorMenuItem", "Schwarz"},
                {"yellowColorMenuItem", "Gelb"},
                {"orangeColorMenuItem", "Orange"},
                {"whiteColorMenuItem", "Weiß"},
                {"ukCountryMenuItem", "UK"},
                {"germanyCountryMenuItem", "Deutschland"},
                {"franceCountryMenuItem", "Frankreich"},
                {"noneCountryMenuItem1", "Keine"},
                {"cancelButton", "Abbrechen"},
                {"okButton", "OK"},
                {"countryMenuBar", "Landsmenü"},
                {"noneCountryMenuItem1", "Keine"},

                {"User:", "Benutzer:"},

                {"Update", "Aktualisieren"},
                {"WrongOwnerException", "Nicht der Besitzer des Filmes"},
                {"NumberFormatException", "Ungültige Zahl"},
                {"NotFoundException", "Film nicht gefunden"},
                {"IOException", "Fehler beim Lesen der Datei"},
                {"Can't read file", "Kann Datei nicht lesen"},
                {"ERROR", "FEHLER"},
                {"OK", "OK"},
                {"Cancel", "Abbrechen"},
                {"WARNING", "WARNUNG"},

                {"Movie", "Film"},
                {"Operator", "Betreiber"},
                {"Genre", "Genre"},
                {"Box office", "Box Office"},
                {"Oscars count", "Oscars-Anzahl"},
                {"Creation date", "Erstellungsdatum"},
                {"Birthday", "Geburtstag"},
                {"Weight", "Gewicht"},
                {"Eye color", "Augenfarbe"},
                {"Nationality", "Nationalität"},

                {"Update", "Aktualisieren"},
                {"Remove", "Entfernen"},
                {"Add", "Hinzufügen"},
                {"Add (if max)", "Hinzufügen (wenn maximal)"},
                {"Update by ID", "Aktualisieren nach ID"},
                {"Remove by ID", "Entfernen nach ID"},
                {"Remove at", "Entfernen nach Position"},

                {"FileChooserTitle", "Datei auswählen"},
                {"delete", "Löschen"},

                {"Visualization", "Visualisierung"},
                {"visualization", "Visualisierung"},

                {"Movie is not presented", "Film nicht angezeigt"},
                {"Movie", "Film"},
                {"opNameLabel", "Name des Betreibers"},
                {"opNameTextField", "Geben Sie Ihren Namen ein:"},
                {"opBirthdayLabel", "Geburtstag des Betreibers"},
                {"opWeightLabel", "Gewicht"},
                {"ocLabel", "Box Office"},
                {"ocTextField", "Geben Sie Ihren Box Office ein:"},
                {"genreLabel", "Genre"},
                {"coordinatesLabel", "Koordinaten"},
                {"coordXLabel", "X-Koordinate"},
                {"coordXTextField", "Geben Sie Ihre X-Koordinate ein:"},
                {"coordYLabel", "Y-Koordinate"},
                {"coordYTextField", "Geben Sie Ihre Y-Koordinate ein:"},
                {"operatorLabel", "Betreiber"},
                {"colorMenuBar", "Farbmenü"},
                {"redColorMenuItem", "Rot"},
                {"blackColorMenuItem", "Schwarz"},
                {"yellowColorMenuItem", "Gelb"},
                {"orangeColorMenuItem", "Orange"},
                {"whiteColorMenuItem", "Weiß"},
                {"ukCountryMenuItem", "UK"},
                {"germanyCountryMenuItem", "Deutschland"},
                {"franceCountryMenuItem", "Frankreich"},
                {"noneCountryMenuItem1", "Keine"},
                {"cancelButton", "Abbrechen"},
                {"okButton", "OK"},
                {"countryMenuBar", "Landsmenü"},
                {"noneCountryMenuItem1", "Keine"},
                {"uboLabel", "Usa Box Office"},
                {"uboTextField", "Geben Sie Ihren Box Office ein:"},


                {"weight", "Gewicht"},
                {"Eye color", "Augenfarbe"},
                {"Nationality", "Nationalität"},
                {"movieNameLabel", "Name des Filmes"},
                {"movieNameTextField", "Geben Sie Ihren Namen ein:"},
                {"movieLabel", "Film"},

                {"tableTab", "Tabelle"},
                {"visualizationTab", "Visualisierung"},

                {"lab8", "Lab8"},

        };
    }
}
