version = 5.1.0
archive_dir = /etc/letsencrypt/archive/cryptoterm.duckdns.org
cert = /etc/letsencrypt/live/cryptoterm.duckdns.org/cert.pem
privkey = /etc/letsencrypt/live/cryptoterm.duckdns.org/privkey.pem
chain = /etc/letsencrypt/live/cryptoterm.duckdns.org/chain.pem
fullchain = /etc/letsencrypt/live/cryptoterm.duckdns.org/fullchain.pem
[renewalparams]
account = 7a09504d2abbe612b79d42c666fb4abb
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
cryptoterm.duckdns.org = /var/www/certbot
