/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.7/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "lab8"
include("server", "common", "client");

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            library("org-slf4j-slf4j-api", "org.slf4j:slf4j-api:2.0.12")
        }
    }
}
