spring:
  profiles:
    active: local

server:
  port: 8761

---
spring:
  config:
    activate:
      on-profile: local
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false

---
spring:
  config:
    activate:
      on-profile: docker
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false